- name: "Instala Apache"
  yum:
    name: httpd
    state: latest


- name: "Sobe Apache"
  service:
    name: httpd
    state: started


- name: "Instala Maria-DB Server"
  yum:
    name: mariadb-server
    state: latest


- name: "Instala Maria-DB Clients"
  yum:
    name: mariadb
    state: latest


- name: "Sobe MariaDB"
  service:
    name: mariadb
    state: started


- name: "Instala PHP"
  yum:
    name: php
    state: latest


- name: "Instala PHP-Mysql"
  yum:
    name: php-mysql
    state: latest


- name: "Instala PHP-GD"
  yum:
    name: php-gd
    state: latest

- name: "Instala Unzip"
  yum:
    name: unzip
    state: latest

- name: "Instala Centos Gluster release"
  yum:
    name: centos-release-gluster37
    state: latest

- name: "Instala Centos Gluster basico"
  yum:
    name: glusterfs
    state: latest

- name: "Instala Centos Gluster clients"
  yum:
    name: glusterfs-cli
    state: latest

- name: "Instala Centos Gluster Libs"
  yum:
    name: glusterfs-libs
    state: latest

- name: "Instala Centos Gluster Fuse"
  yum:
    name: glusterfs-fuse
    state: latest

- name: "Setenforce Linux 0"
  selinux:
    state: disabled


- name: "Copia Welcome zerado para /etc/httpd/conf.d/welcome.conf"
  copy:
   src: "{{ role_path }}/files/welcome.conf"
   dest: /etc/httpd/conf.d/welcome.conf

- name: "Restarta Apache"
  service:
   name: httpd
   state: restarted

- name: "Copia template SQL para /tmp"
  copy:
   src: "{{ role_path }}/files/sql/sql_creation.sql"
   dest: /tmp/sql_creation.sql



- name: "Cria database e tabelas..."
  shell: "mysql -u root < /tmp/sql_creation.sql"

- name: "Copia template bootstrap para /var/www/html"
  copy:
   src: "{{ role_path }}/files/app/app.tar.gz"
   dest: /var/www/html/app.tar.gz

- name: "Descompacta template"
  unarchive:
    src: /var/www/html/app.tar.gz
    dest: /var/www/html/
    remote_src: yes
