- name: Snapshot instancias Gcloud Gluster
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: conta1@infra-as-code.iam.gserviceaccount.com
    credentials_file: /etc/ansible/local_files/gcloud.json
    project_id: infra-as-code
    machine_type: n1-standard-2
    machine_type_node: n1-standard-1
    zone: southamerica-east1-b
    image: rhel-7
    tamanho_disco: 40
    tamanho_disco_grande: 50
    tamanho_disco_adicional: 50

  tasks:

  - name: Snapshot Instancia Bastion
    gce_snapshot:
        instance_name: bastion
        snapshot_name: bastion-snapshot
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

  - name: Snapshot Instancia Master1
    gce_snapshot:
        instance_name: master1
        snapshot_name: master1-snapshot
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

  - name: Snapshot Instancia Infranode
    gce_snapshot:
        instance_name: infra-node1
        snapshot_name: infra-node1-snapshot
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

  - name: Snapshot Instancia Node1
    gce_snapshot:
        instance_name: node1
        snapshot_name: node1-snapshot
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

  - name: Snapshot Instancia Node2
    gce_snapshot:
        instance_name: node2
        snapshot_name: node2-snapshot
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"


