service_account_email: adminwsansible@workshopansiblecoreandtower.iam.gserviceaccount.com 
credentials_file: /home/luciano/gce.json
project_id: workshopansiblecoreandtower 
chave_ssh: /home/luciano/.ssh/gce
usuario_ssh_gce: luciano
endereco_tower: https://35.198.12.187
cluster_openshift: 35.198.30.2
nome_projeto_openshift: workshop
token_openshift: 0-bJSfthualhOtv16voY6ApgM308voeankEcaLt51WM
email_remetente: redhatbsb@gmail.com
nome_workshop: workshop-ansible-rio
