service_account_email: adminwsansible@workshopansiblecoreandtower.iam.gserviceaccount.com 
credentials_file: /home/luciano/gce.json
project_id: workshopansiblecoreandtower 
chave_ssh: /home/luciano/.ssh/gce
usuario_ssh_gce: luciano
