- name: Cria instancias Gcloud Openshift para Workshop
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    machine_type_node: n1-standard-1
    zone: southamerica-east1-a
    image: centos-7
    preemptible: true
    tamanho_disco_pequeno: 40
    tamanho_disco_grande: 50
    tamanho_disco_adicional: 50
    master_private_ip: ""
    infranode_private_ip: ""
    node1_private_ip: ""

  vars_prompt:
  - name: "user"
    prompt: "Digite o login do estudante para criacao da instancia:"
    private: no

  tasks:

  - name: Carregando variaveis de config.yml
    include_vars: config.yml

  - name: "Cria Disco 1 instancia {{ user }}"
    gce_pd:
      name: "{{ user }}disk01"
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco_pequeno }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: "Cria Disco 1 instancia {{ user }}-server1"
    gce_pd:
      name: "{{ user }}disk02"
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco_pequeno }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: "Cria Disco 1 instancia {{ user }}-server2"
    gce_pd:
      name: "{{ user }}disk03"
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco_pequeno }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"


  - name: "Cria Instancia {{ user }}"
    gce:
        instance_names: "{{ user }}"
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        preemptible: "{{ preemptible }}"
        tags:
         - http-server
         - https-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
        - name: "{{ user }}disk01"
          mode: READ_WRITE
    register: gce_node

  - name: "Cria Instancia {{ user }}-server1"
    gce:
        instance_names: "{{ user }}-server1"
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        external_ip: none
        preemptible: "{{ preemptible }}"
        tags:
         - http-server
         - https-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
        - name: "{{ user }}disk02"
          mode: READ_WRITE

  - name: "Cria Instancia {{ user }}-server2"
    gce:
        instance_names: "{{ user }}-server2"
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        external_ip: none
        preemptible: "{{ preemptible }}"
        tags:
         - http-server
         - https-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
        - name: "{{ user }}disk03"
          mode: READ_WRITE

  - name: Salva dados no grupo de inventario... usuario
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: gce_instances_ips
    with_items: "{{ gce_node.instance_data }}"


  - name: Espera por SSH habilitado...
    wait_for:
      delay: 1
      host: "{{ item.public_ip }}"
      port: 22
      state: started
      timeout: 30
    with_items: "{{ gce_node.instance_data }}"

  - name: Adiciona usuario no tower
    tower_user:
      username: "{{ user }}"
      password: redhat
      email: usuario@redhat.com
      first_name: "{{ user }}"
      last_name: RedHat
      state: present
      tower_config_file: "tower_cli.cfg"


  - name: "Seta variaveis para proximos passos"
    set_fact: 
      chave_ssh: "{{ chave_ssh }}"
      usuario_ssh_gce: "{{ usuario_ssh_gce }}"

- name: "Configura Hosts seguindo roles... {{ hostvars['localhost']['chave_ssh'] }} "
  vars:
   ansible_ssh_private_key_file: "{{ hostvars['localhost']['chave_ssh'] }}"
  hosts: gce_instances_ips
  become: yes
  become_method: sudo
  remote_user: "{{ hostvars['localhost']['usuario_ssh_gce'] }}"
  roles:
    - postinstall
