- name: Cria instancia Ansible1
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: conta1@infra-as-code.iam.gserviceaccount.com
    credentials_file: /etc/ansible/local_files/gcloud.json
    project_id: infra-as-code
    machine_type: n1-standard-2
    machine_type_node: n1-standard-1
    zone: southamerica-east1-b
    image: centos-7
    tamanho_disco: 50
    php_private_ip: ""
    jc_private_ip: ""


  tasks:

  - name: Cria liberacao porta 80 e 443
    gce_net:
      name: default
      fwname: "openshift-80443"
      allowed: tcp:80,443
      state: "present"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: Cria Disco 1 Ansible
    gce_pd:
      name: ansibledisk01
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: Cria Disco 2 Ansible
    gce_pd:
      name: ansibledisk02
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      
  - name: Cria Instancia Ansible01
    gce:
        instance_names: ansible01
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        tags:
         - http-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
        - name: ansibledisk01
          mode: READ_WRITE
    register: gce_ansible1


  - name: Cria Instancia Ansible02
    gce:
        instance_names: ansible02
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        tags:
         - http-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
        - name: ansibledisk02
          mode: READ_WRITE
    register: gce_ansible2


  - name: Salva dados no grupo de inventario... ansible
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: gce_instances_ips
    with_items: "{{ gce_ansible1.instance_data }}"

  - name: Seta variavel ip privado ansible
    set_fact:
      ansible_ip: "{{ item.private_ip }}"
    with_items: "{{ gce_ansible1.instance_data }}"

  - name: Salva dados no grupo de inventario... ansible
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: gce_instances_ips
    with_items: "{{ gce_ansible2.instance_data }}"

  - name: Seta variavel ip privado ansible
    set_fact:
      ansible_ip: "{{ item.private_ip }}"
    with_items: "{{ gce_ansible2.instance_data }}"


  - name: Espera por SSH habilitado...
    wait_for:
      delay: 1
      host: "{{ item.public_ip }}"
      port: 22
      state: started
      timeout: 30
    with_items: "{{ gce_ansible2.instance_data }}"

#- name: Configura Hosts seguindo roles...
#  vars:
#   ansible_ssh_private_key_file: /home/luciano/gce.pem
#  hosts: gce_instances_ips
#  become: yes
#  become_method: sudo
#  remote_user: luciano
#  roles:
#    - ansible
