- name: Remove instancias Gcloud Gluster
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: conta1@infra-as-code.iam.gserviceaccount.com
    credentials_file: /etc/ansible/local_files/gcloud.json
    project_id: infra-as-code
    machine_type: n1-standard-2
    machine_type_node: n1-standard-1
    zone: southamerica-east1-b
    image: centos-7
    tamanho_disco: 50

  tasks:


  - name: Remove Instancia Ansible01
    gce:
        instance_names: ansible01
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        state: "deleted"
        tags:
         - http-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
        - name: ansibledisk01
          mode: READ_WRITE

  - name: Remove Instancia Ansible02
    gce:
        instance_names: ansible02
        machine_type: "{{ machine_type_node }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        state: "deleted"
        tags:
         - http-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
        - name: ansibledisk02
          mode: READ_WRITE



  - name: Deleta Disco 1 ansible
    gce_pd:
      name: ansibledisk01
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      state: "deleted"

  - name: Deleta Disco 2 ansible
    gce_pd:
      name: ansibledisk02
      image: "{{ image }}"
      size_gb: "{{ tamanho_disco }}"
      zone: "{{ zone  }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      state: "deleted"

